version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: movis-postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: movis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movis
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
